version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
